### ISSUE TITLE
error on create example (NoMethodError)

### ISSUE THREAD

**Issue by ssoto2** [tongueroo/lono#38]
when going through the example i get the following error during the create

```
lono cfn create ec2
Using template: output/templates/ec2.yml
Using parameters: config/params/development/ec2.txt
Creating ec2 stack...
No detected app/scripts
Generating CloudFormation templates:
  output/templates/ec2.yml
  output/params/ec2.json
/home/ssoto/gems/gems/lono-4.2.4/lib/lono/cfn/base.rb:263:in `show_parameters': undefined method `compact' for #<Hash:0x0055dcb7aea210> (NoMethodError)
	from /home/ssoto/gems/gems/lono-4.2.4/lib/lono/cfn/create.rb:35:in `create_stack'
	from /home/ssoto/gems/gems/lono-4.2.4/lib/lono/cfn/create.rb:6:in `save_stack'
	from /home/ssoto/gems/gems/lono-4.2.4/lib/lono/cfn/base.rb:35:in `run'
	from /home/ssoto/gems/gems/lono-4.2.4/lib/lono/cfn.rb:38:in `create'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/ssoto/gems/gems/lono-4.2.4/lib/lono/command.rb:43:in `dispatch'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/ssoto/gems/gems/lono-4.2.4/lib/lono/command.rb:43:in `dispatch'
	from /home/ssoto/gems/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/ssoto/gems/gems/lono-4.2.4/exe/lono:11:in `<top (required)>'
	from /home/ssoto/gems/bin/lono:22:in `load'
	from /home/ssoto/gems/bin/lono:22:in `<main>'
```

key info 

```
lono -v
4.2.4
```

```
ruby -v
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

```
gem list

*** LOCAL GEMS ***

activesupport (5.2.2)
aws-eventstream (1.0.1)
aws-partitions (1.123.0)
aws-sdk-cloudformation (1.13.0)
aws-sdk-core (3.44.0)
aws-sdk-kms (1.13.0)
aws-sdk-s3 (1.30.0)
aws-sigv4 (1.0.3)
bigdecimal (1.2.8)
bundler (1.17.2)
coderay (1.1.2)
colorize (0.8.1)
concurrent-ruby (1.1.3)
did_you_mean (1.0.0)
ffi (1.9.25)
filesize (0.2.0)
formatador (0.2.5)
graph (2.8.2)
guard (2.15.0)
guard-cloudformation (0.0.3)
guard-compat (1.2.1)
guard-lono (1.0.1)
hashie (3.6.0)
i18n (1.2.0)
io-console (0.4.5)
jmespath (1.4.0)
json (2.1.0, 1.8.3)
listen (3.1.5)
lono (4.2.4)
lumberjack (1.0.13)
memoist (0.16.0)
method_source (0.9.2)
minitest (5.11.3, 5.10.3)
nenv (0.3.0)
net-telnet (0.1.1)
notiffany (0.1.1)
power_assert (0.2.7)
pry (0.12.2)
psych (2.1.0)
rake (12.0.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (4.2.1)
render_me_pretty (0.8.1)
ruby_dep (1.5.0)
shellany (0.0.1)
test-unit (3.2.5)
thor (0.20.3)
thread_safe (0.3.6)
tilt (2.0.9)
top (0.0.1)
tzinfo (1.2.5)
```

**Comment by tongueroo** [comment]
I see. Can you try upgrading to ruby 2.5.3. Will have to update this.

**Comment by tongueroo** [comment]
Close from inactivity
